### ISSUE TITLE
Example of including ArcGIS map has wrong title and needs scrolling

### ISSUE THREAD

**Issue by smalers** [OpenWaterFoundation/owf-lib-viz-fullpagejs-story#7]
The section that shows an embedded Esri map is mislabeled "Embed a Video".  It should be something like "Embed ArcGis Online Map" (check with Kristin).  Also, can the text on the page be scrolled on the same page rather than bleeding into next page.  Justin had figured out how to scroll long text in the same section.

**Comment by marcelaf7** [comment]
Changed title to "Embed an ArcGIS Map". Closed issue.
