### ISSUE TITLE
Need example of Leaflet filling more space

### ISSUE THREAD

**Issue by smalers** [OpenWaterFoundation/owf-lib-viz-fullpagejs-story#8]
The Leaflet example is good.  However, it would be good to have additional examples such as:

1) Rather than including a buffer around the map, have the map fill the entire available space (other than the text area).  This is what Esri Story maps do.

2) Have the map fill the entire section and figure out how to have floating text on top, sort of like how the image example has text on top.   In this case, the text will presumably be relatively small so the map is able to dominate.

3) Will this apply to the Juxtapose example also?  Maybe also need one or two additional examples of that.

**Comment by marcelaf7** [comment]
Added a section titled "Full Page Leaflet Map" with a map filling most of the available space(with some empty space to allow the user to scroll to the next page). 

Juxtapose will have a hard time with a full screen example. It must stay at the same ratio as the images it was made from. If the window is ever a different ratio, it will cause sizing issues that either create a lot of empty space on the screen or hide important parts of the image off-screen.

Close issue.
